version: '3.7'

services:

 db:
  container_name: db
  image: mysql
  #restart: unless-stopped
  networks:
   network-handytec:
    aliases:
     - db
  volumes:
   - ./db.sql:/docker-entrypoint-initdb.d/db.sql
  environment:
   - MYSQL_DATABASE=handytec
   - MYSQL_USER=handytec
   - MYSQL_PASSWORD=handytec
   - MYSQL_ROOT_PASSWORD=root
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-authentication-plugin=mysql_native_password]

 app:
  container_name: app
  image: localhost/handytec
  #restart: unless-stopped
  volumes:
   - ./html:/var/www/html
  networks:
   - network-handytec
  ports:
   - 80:80
  build:
   context: .
   dockerfile: Dockerfile

networks:
 network-handytec:
  name: network-handytec

