version: '3.7'

services:

 app:
  build:
   context: ./app
   args:
    - IMAGE=${APP_IMAGE}
    - VERSION=${APP_VERSION}
  container_name: ${APP_NAME}
  depends_on:
    - db
  image: localhost/search-and-replace:${APP_VERSION}

 db:
  # Build is need becasue if the 'docker-compose up' command is executed from within a docker container (for instance jenkins node) the volume will not work, will be empty
  build:
   context: ./db
   args:
    - IMAGE=${DB_IMAGE}
    - VERSION=${DB_VERSION}
  container_name: ${DB_NAME}
  environment:
   - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
   - MYSQL_USER=${DB_MYSQL_USER}
   - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
   - MYSQL_ROOT_PASSWORD=${DB_MYSQL_ROOT_PASSWORD}
  image: ${DB_IMAGE}:${DB_VERSION}
  # The .sql file (if any) will be copied at build time, because if the 'docker-compose up' command is executed from within a docker container (for instance jenkins node) the volume will not work, will be empty
  #volumes:
  # - ./db:/docker-entrypoint-initdb.d
