version: '3.7'

services:

 db:
  container_name: ${DB_NAME}
  image: ${DB_IMAGE}:${DB_VERSION}
  #restart: unless-stopped
  networks:
   network-handytec:
    aliases:
     - ${DB_NAME}
  volumes:
   - ./${DB_BACKUP_FILENAME}:/docker-entrypoint-initdb.d/${DB_BACKUP_FILENAME}
  environment:
   - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
   - MYSQL_USER=${DB_MYSQL_USER}
   - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
   - MYSQL_ROOT_PASSWORD=${DB_MYSQL_ROOT_PASSWORD}

 app:
  container_name: ${APP_NAME}
  image: localhost/handytec:${APP_VERSION}
  #restart: unless-stopped
  volumes:
   - ./${APP_HTML}:/var/www/html
  networks:
   - network-handytec
  ports:
   - ${APP_PORT_HOST}:${APP_PORT_CONTAINER}
  build:
   context: ./app
   args:
    - IMAGE=${APP_IMAGE}
    - VERSION=${APP_VERSION}

networks:
 network-handytec:
  name: ${NETWORK_HANDYTEC}

